# Generated by Django 4.0.5 on 2022-06-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='posts.post'),
        ),
    ]
